spring.application.name=BlogApp
#
#
#
#spring.datasource.url=jdbc:mysql://localhost:3306/blog_app?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#
#
#spring.datasource.username=root
#spring.datasource.password=123456789
#spring.jpa.hibernate.ddl-auto=update
##spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect //? THis is Deprecated Version
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#
#spring.jpa.show-sql=true
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
##spring.data.rest.base-path=/api
#
#
#spring.main.banner-mode = off
#
#logging.level.root=warn
#
#
#
##spring.security.user.name=hussein
##spring.security.user.password=hussein
##spring.security.user.roles=ADMIN

#! JWT

app.jwt-secret=3a4a037aa3ee8e56470091e5c57201dd8ea08343d0dc91e63302ffb61f0cabee
app.jwt-expiration-milliseconds=604800000
#! 604,800,000 = 7 days

spring.profiles.active=dev








